<?php

namespace ContainerXaWOxIn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QcUgbUpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qcUgbUp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qcUgbUp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'parcour' => ['privates', '.errored..service_locator.qcUgbUp.App\\Entity\\Parcours', NULL, 'Cannot autowire service ".service_locator.qcUgbUp": it references class "App\\Entity\\Parcours" but no such service exists.'],
        ], [
            'parcour' => 'App\\Entity\\Parcours',
        ]);
    }
}
