<?php

namespace Container8AgDAwF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BCSOUecService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BCSOUec' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BCSOUec'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'experienceRepository' => ['privates', 'App\\Repository\\ExperienceRepository', 'getExperienceRepositoryService', true],
        ], [
            'experienceRepository' => 'App\\Repository\\ExperienceRepository',
        ]);
    }
}
