<?php

namespace Container8AgDAwF;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N_1n13Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._n.1n13' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._n.1n13'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'presentationRepository' => ['privates', 'App\\Repository\\PresentationRepository', 'getPresentationRepositoryService', true],
        ], [
            'presentationRepository' => 'App\\Repository\\PresentationRepository',
        ]);
    }
}
