<?php

namespace ContainerRnMXkop;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8ZHgH5vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ZHgH5v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ZHgH5v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'realisationRepository' => ['privates', 'App\\Repository\\RealisationRepository', 'getRealisationRepositoryService', true],
        ], [
            'realisationRepository' => 'App\\Repository\\RealisationRepository',
        ]);
    }
}
