<?php

namespace Container36x0Rt6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRealisationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Q6MNAd4.App\Entity\Realisation' shared service.
     *
     * @return \App\Entity\Realisation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Q6MNAd4": it references class "App\\Entity\\Realisation" but no such service exists.');
    }
}
