<?php

namespace ContainerGVgacw9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_28o3U_XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.28o3U.X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.28o3U.X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competencesCategoriesRepository' => ['privates', 'App\\Repository\\CompetencesCategoriesRepository', 'getCompetencesCategoriesRepositoryService', true],
        ], [
            'competencesCategoriesRepository' => 'App\\Repository\\CompetencesCategoriesRepository',
        ]);
    }
}
