<?php

namespace ContainerGVgacw9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gk44A0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gk_44A0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gk_44A0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'experience' => ['privates', '.errored..service_locator.Gk_44A0.App\\Entity\\Experience', NULL, 'Cannot autowire service ".service_locator.Gk_44A0": it references class "App\\Entity\\Experience" but no such service exists.'],
        ], [
            'experience' => 'App\\Entity\\Experience',
        ]);
    }
}
