<?php

namespace Container3HTev97;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ti_LzZiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ti.lzZi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ti.lzZi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoriesRepository' => ['privates', 'App\\Repository\\CompetencesCategoriesRepository', 'getCompetencesCategoriesRepositoryService', true],
            'competencesRepository' => ['privates', 'App\\Repository\\CompetencesRepository', 'getCompetencesRepositoryService', true],
        ], [
            'categoriesRepository' => 'App\\Repository\\CompetencesCategoriesRepository',
            'competencesRepository' => 'App\\Repository\\CompetencesRepository',
        ]);
    }
}
