<?php

namespace Container3HTev97;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Http\Api\Controller\Utils' shared autowired service.
     *
     * @return \App\Http\Api\Controller\Utils
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Utils.php';

        return $container->services['App\\Http\\Api\\Controller\\Utils'] = new \App\Http\Api\Controller\Utils();
    }
}
