<?php

namespace ContainerIeHmKTG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedirectUtilsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Utils\Http\RedirectUtils' shared autowired service.
     *
     * @return \App\Utils\Http\RedirectUtils
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Utils'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'RedirectUtils.php';

        $container->services['App\\Utils\\Http\\RedirectUtils'] = $instance = new \App\Utils\Http\RedirectUtils(($container->privates['Symfony\\Component\\HttpFoundation\\Request'] ?? ($container->privates['Symfony\\Component\\HttpFoundation\\Request'] = new \Symfony\Component\HttpFoundation\Request())));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('App\\Utils\\Http\\RedirectUtils', $container));

        return $instance;
    }
}
