<?php

namespace ContainerGhbHz4c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YvIznsyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yvIznsy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yvIznsy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competencesCategory' => ['privates', '.errored..service_locator.yvIznsy.App\\Entity\\CompetencesCategories', NULL, 'Cannot autowire service ".service_locator.yvIznsy": it references class "App\\Entity\\CompetencesCategories" but no such service exists.'],
        ], [
            'competencesCategory' => 'App\\Entity\\CompetencesCategories',
        ]);
    }
}
