<?php

namespace ContainerGhbHz4c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F8KYUgnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F8KYUgn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F8KYUgn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'realisationRepository' => ['privates', 'App\\Repository\\RealisationRepository', 'getRealisationRepositoryService', true],
        ], [
            'paginator' => '?',
            'realisationRepository' => 'App\\Repository\\RealisationRepository',
        ]);
    }
}
