<?php

namespace ContainerGhbHz4c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetencesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kvkaJ38.App\Entity\Competences' shared service.
     *
     * @return \App\Entity\Competences
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kvkaJ38": it references class "App\\Entity\\Competences" but no such service exists.');
    }
}
