<?php

namespace ContainerB7doBr4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KvkaJ38Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kvkaJ38' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kvkaJ38'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'competence' => ['privates', '.errored..service_locator.kvkaJ38.App\\Entity\\Competences', NULL, 'Cannot autowire service ".service_locator.kvkaJ38": it references class "App\\Entity\\Competences" but no such service exists.'],
        ], [
            'competence' => 'App\\Entity\\Competences',
        ]);
    }
}
