<?php

namespace ContainerB7doBr4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBasketControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Http\Api\Controller\BasketController' shared autowired service.
     *
     * @return \App\Http\Api\Controller\BasketController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Http'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'BasketController.php';

        return $container->services['App\\Http\\Api\\Controller\\BasketController'] = new \App\Http\Api\Controller\BasketController();
    }
}
