<?php

namespace ContainerACpqScC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SIQEE3_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sIQEE3.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sIQEE3.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'presentation' => ['privates', '.errored..service_locator.sIQEE3..App\\Entity\\Presentation', NULL, 'Cannot autowire service ".service_locator.sIQEE3.": it references class "App\\Entity\\Presentation" but no such service exists.'],
        ], [
            'presentation' => 'App\\Entity\\Presentation',
        ]);
    }
}
