<?php

namespace ContainerACpqScC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompetencesCategoriesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yvIznsy.App\Entity\CompetencesCategories' shared service.
     *
     * @return \App\Entity\CompetencesCategories
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yvIznsy": it references class "App\\Entity\\CompetencesCategories" but no such service exists.');
    }
}
