<?php

namespace ContainerACpqScC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPresentationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sIQEE3..App\Entity\Presentation' shared service.
     *
     * @return \App\Entity\Presentation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.sIQEE3.": it references class "App\\Entity\\Presentation" but no such service exists.');
    }
}
