<?php

namespace ContainerEovLXiI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__9_RL3dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..9.rL3d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..9.rL3d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'member' => ['privates', '.errored..service_locator..9.rL3d.App\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator..9.rL3d": it references class "App\\Entity\\Member" but no such service exists.'],
            'memberRepository' => ['privates', 'App\\Repository\\MemberRepository', 'getMemberRepositoryService', true],
        ], [
            'member' => 'App\\Entity\\Member',
            'memberRepository' => 'App\\Repository\\MemberRepository',
        ]);
    }
}
