<?php

namespace ContainerEovLXiI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GkXnqK9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GkXnqK9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GkXnqK9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'memberRepository' => ['privates', 'App\\Repository\\MemberRepository', 'getMemberRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'memberRepository' => 'App\\Repository\\MemberRepository',
            'paginator' => '?',
        ]);
    }
}
