<?php

namespace ContainerA8999MY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q6MNAd4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q6MNAd4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q6MNAd4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'realisation' => ['privates', '.errored..service_locator.Q6MNAd4.App\\Entity\\Realisation', NULL, 'Cannot autowire service ".service_locator.Q6MNAd4": it references class "App\\Entity\\Realisation" but no such service exists.'],
        ], [
            'realisation' => 'App\\Entity\\Realisation',
        ]);
    }
}
