<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIeHmKTG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIeHmKTG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIeHmKTG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIeHmKTG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIeHmKTG\App_KernelDevDebugContainer([
    'container.build_hash' => 'IeHmKTG',
    'container.build_id' => 'dd57241a',
    'container.build_time' => 1620598266,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIeHmKTG');
