<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHnH8etm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHnH8etm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHnH8etm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHnH8etm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHnH8etm\App_KernelDevDebugContainer([
    'container.build_hash' => 'HnH8etm',
    'container.build_id' => '573e26fa',
    'container.build_time' => 1622447904,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHnH8etm');
