<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM5Q1hVs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM5Q1hVs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM5Q1hVs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM5Q1hVs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM5Q1hVs\App_KernelDevDebugContainer([
    'container.build_hash' => 'M5Q1hVs',
    'container.build_id' => '893e66dd',
    'container.build_time' => 1620938490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM5Q1hVs');
